# Generated by Django 3.0.5 on 2020-05-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=50, unique=True)),
                ('host_group', models.CharField(max_length=20, null=True)),
                ('internal_ip', models.GenericIPAddressField(protocol='ipv4', unique=True)),
                ('external_ip', models.GenericIPAddressField(null=True, protocol='ipv4', unique=True)),
                ('host_memory', models.IntegerField()),
                ('host_cpu', models.IntegerField()),
            ],
        ),
    ]
