# Generated by Django 3.0.5 on 2020-05-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20200530_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='host_group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
