# Generated by Django 3.0.5 on 2020-05-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20200530_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='external_ip',
            field=models.GenericIPAddressField(default='0', protocol='ipv4', unique=True),
        ),
    ]
