# Generated by Django 3.0.5 on 2020-05-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20200530_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='external_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='ipv4', unique=True),
        ),
    ]
